# Generated by Django 3.0.3 on 2022-05-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthInsurance', '0002_auto_20220530_2221'),
        ('healthInsurance', '0003_auto_20220530_2143'),
    ]

    operations = [
    ]
